---
title: "R GIT"
output:
  html_document:
    df_print: paged
  pdf_document: default
---

## Install Git

```{Bash}
which git
git --version ## git version 2.34.1
```

## Configure Git Globally using Terminal

```{Bash}
git config --global user.name "*****"
git config --global user.email "********"
git config --list
```

## Configure Git Globally using Rstudio

```{r}
#Edit the .gitconfig file that pops up as below
library(usethis)
usethis::edit_git_config() #In Ubuntu toggle the hidden files
```

```{bash}
[user]
	name = *****
	email = *****************
```

```{r}
#Another way is to perform the same global config procedure in Rstudio
use_git_config(user.name = "*****", user.email = "***********")
```

## Interfacing with Github

```{r}
#usethis is used for token generation
#a token i put online ridiculous: ********(I hid it and that rpubs document will be discarded shortly after this concise git and github Rstudio notebook)
#what can i say i am smarter now.
usethis::create_github_token()

#Passing the baton to gitcreds
#this procedure is performed outside a project otherwise it fails
gitcreds::gitcreds_set()
#? Enter password or token: ***************
use_github() #creates the repo on github
```


## End Remarks

- Completed a setup of git and github with Rstudio in Ubuntu.
- Happy gitting.